sudo: required
dist: trusty

os: linux

language: c

env:
  globals:
    - TEST_NGINX_BINARY=openresty

addons:
  apt:
    packages:
    - cpanminus
    - luarocks
    - valgrind

before_install:
  - sudo luarocks install luacheck
#  - luacheck -q .
  - sudo cpanm --notest Test::Nginx > build.log 2>&1 || (cat build.log && exit 1)

install:
  - wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
  - sudo apt-get -y install libpcre3-dev libssl-dev perl make build-essential curl
  - sudo wget https://openresty.org/download/openresty-1.13.6.1.tar.gz
  - sudo tar -xzvf openresty-1.13.6.1.tar.gz 1>/dev/null
  - cd openresty-1.13.6.1/
  - sudo ./configure --without-http_lua_upstream_module
  - sudo make
  - sudo make install
script:
  - export PATH=$PATH:/usr/local/openresty/nginx/sbin
  - /usr/local/openresty/nginx/sbin/nginx -V
  - prove -r t
  - bash test_with_valgrind.sh
